### ISSUE TITLE
Can you do a non-blocking version or lock-free queue?

### ISSUE THREAD

**Issue by OscarTHZhang** [syuan16/Java-Concurrency#1]

**Comment by syuan16** [comment]
What's the point of having a concurrent queue without any lock guarding?

**Comment by OscarTHZhang** [comment]
It's going to be faster than locking version as CPU will not waste cycle on locking

**Comment by syuan16** [comment]
How do you prevent race condition

**Comment by syuan16** [comment]
Or do you mean do nothing if the queue is empty (consumer) or full (producer)?

**Comment by OscarTHZhang** [comment]
Atomic operation with memory order
